spring:
  data:
    mongodb:
      uri: mongodb+srv://${DB_USER:fabianojp06}:${DB_PASSWORD}3EAiYFymmLQo8Nak@cluster0.twr0grn.mongodb.net/{DB_NAME:webfluxcurso}?retryWrites=true&w=majority
      auto-index-creation: true